### ISSUE TITLE
Automation not working properly on Android 13

### ISSUE THREAD

**Issue by jcoin** [bfabiszewski/ulogger-android#116]
I'm trying to use Tasker to automate when to start and to stop location recording.

Sending the "stop logger" command works as expected, but the commands "start logger" and "start new logger" don't.
I use exactly the same action parameters; I only change the command name.

Location permission has been given "all the time".
I'm not sure what I'm doing wrong, does anyone else have the same issue ?

**Comment by bfabiszewski** [comment]
Thanks for the report.
I'll try to reproduce it in emulator.

**Comment by bfabiszewski** [comment]
I did some testing and it seems that on Android 12+ you have to disable battery optimization for µlogger.
Otherwise the service can't be started from background.
Please check if it works also for you with battery usage set as unrestricted for the app.

Anyway the battery optimization should be disabled for µlogger in order to work reliably. I will have to include warning in the application.

**Comment by jcoin** [comment]
Thanks.
Disabling battery optimization solved the problem for me.
