### ISSUE TITLE
Burst upload generates 503 on my server

### ISSUE THREAD

**Issue by think-nice-things** [bfabiszewski/ulogger-android#121]
Hi,

if I do _not_ live synchronization but rather a manual upload of (many) data points, my server returns a 503 "Service unavailable".
Most of the time this is after having uploaded 50 data points.
If I then wait some seconds and trigger another upload, the next 50 data points are uploaded until the server again returns a 503 error.

Most likely this is due to the configuration if my internet service provider -- I guess they've enabled some measures to prevent burst access.
The problem is that I can't do anything about it because I've no direct influence on the apache configuration.

I've two ideas or feature request which would probably solve my problem:

1. if ulogger would offer a **"throttle" option like "maximal number of uploads per second"** I could probably tune this value such that my server doesn't return a 503 error.
2. if ulogger **receives a 503 error and automatically would retry after some time** this would probably also solve my issue.

![Screenshot_20230127-193649_μlogger](https://user-images.githubusercontent.com/4885370/215221085-60d4af32-ada1-4d12-997a-2b22ebee926a.png)

**Comment by bfabiszewski** [comment]
The upload strategy is optimized for live synchro. The idea is that with poor network coverage in remote areas it tries to push the locations one by one instead of sending a package of multiple locations. It assures that if the connection is broken only one location has to be resend, not the whole package of many locations.
In your case however it would be better to send the locations in bunches. It would be nice to have an option in the application to choose the upload strategy. I've been already considering such a solution for some time. This is not a high priority but I will try to implement it when I find some free time.

As a temporary workaround you can consider using a scheduler app like tasker to trigger upload multiple times at some time intervals.
