### ISSUE TITLE
Upload to local Server failed

### ISSUE THREAD

**Issue by imothep666** [bfabiszewski/ulogger-android#17]
Upload to local Server failed with the error message: "Expected literal value at character 0 of /"

**Comment by bfabiszewski** [comment]
I suppose there is some problem with server configuration. 
It seems that server outputs some unexpected response.

You may try to open client upload page (`www.your-domain.org/client/index.php`) from your browser. Properly configured server should display:
`{"error":false}`

**Comment by imothep666** [comment]
I have opened 127.0.0.1/client/index.php and the output was "/{"error":false}" - i use it on a local systemand the ulogger folder and all subdirectories have read write and execute rights.

Thanks

**Comment by bfabiszewski** [comment]
Is the output literally `/{"error":false}`, with the slash character at the beginning? Or is it just a typo?

**Comment by imothep666** [comment]
it is not a typo - i have tried it another time and now there is only "/" as output

**Comment by bfabiszewski** [comment]
So that's definitely your problem. Make sure you didn't accidentally add "/" character to any file including config file.
If you don't find anything strange, please try to reinstall the whole application.

Solving this will probably also solve the other issue you reported: bfabiszewski/ulogger-server#30

**Comment by imothep666** [comment]
thank you - the fix of the other issue fixed this issue too.
