### ISSUE TITLE
Comparison to GPSLogger?

### ISSUE THREAD

**Issue by ser** [bfabiszewski/ulogger-android#42]
Hi, have you ever compared your software to https://gpslogger.app/ ?

Is it possible to use the gpslogger to update your server? 

I am asking because gpslogger has slightly better user interface, especially on modern android, it stays on very thin notification area and takes less screen than ulogger.

**Comment by bfabiszewski** [comment]
I don't plan to add support for GPSLogger client. The topic has already been discussed on [ulogger-server issues](https://github.com/bfabiszewski/ulogger-server/issues/36), where it belongs.

GPSLogger is probably one of the best track loggers with lots of features and active support.
I started my own project because I wanted to have a solution tailored exactly to my needs. That's why I don't want to expand µLogger beyond its micro-functionalities. The other problem with extending µLogger is my lack of time for introducing and supporting new features.
