### ISSUE TITLE
l10n: Double "%" sign

### ISSUE THREAD

**Issue by Valdnet** [bfabiszewski/ulogger-android#84]
There is a double "%" sign in the text string. Shouldn't there be only one?

`If you need literal percent character use %%.`

https://github.com/bfabiszewski/ulogger-android/blob/c3bc85b72f19318766433098979b81021bfa95a9/app/src/main/res/values/strings.xml#L62

**Comment by bfabiszewski** [comment]
Thanks for the info. This is correct.
It is a way to allow users to use literal percent character in their template. If you use `%H` it will be substituted with current hour, eg. `11`. But someone might want to have a template that has `%H` in the name without any substitution. And they can achieve it by writing `%%H` in their template. Then instead of `11` the effective string will be `%H`.
