### ISSUE TITLE
cannot collect network position data

### ISSUE THREAD

**Issue by TjrGithub** [bfabiszewski/ulogger-android#94]
I would expect ulogger to access network position data.
Up to yesterday, I had an old version running that could do so. However, whenever I do a fresh install now, it claims network data is not available, and will not add position points to the database.

Same version information as in #93, except I deleted the app and reinstalled it from fdroid.
No workaround known.

**Comment by bfabiszewski** [comment]
I think the clue is https://github.com/bfabiszewski/ulogger-android/issues/93#issuecomment-753502131.

I don't know how to reproduce your issues on Android 10 where GPS source is bound to general location setting. I don't see an option in OS to disable GPS and leave only network provider.

Setting location provider from within the app works fine. If you choose only network in µlogger settings the application will only listen to updates from network provider.

**Comment by TjrGithub** [comment]
It turns out, ulogger can very well collect network data. But it refuses to start running network-only, and it gives toast messages to the effect of no-position-source-found. But when I start a track with gps+network and leave it running for a while, I can verify with termux+sqlite3 on the device that network position data does accumulate in the database.

Curiously, there tend to be 2-3 times as many gps data points as network data points. (I've set it to collect every 5 seconds, no server sync, everything else as unrestrictive as possible).

**Comment by bfabiszewski** [comment]
When you start the application it checks if there is at least one enabled provider. If it refuses to start it most probably means that all chosen providers are disabled. The idea is to prevent users start tracking with disabled providers by mistake.

When you start application with providers enabled and later disable all providers the application will stay on waiting for any of the providers to be enabled again.

The frequency of the updates depends on app settings but also on the implementation of data gathering by the particular device and it given scenario. The parameters are minimum requirements, so the updates should not happen more often than the settings but the OS is free to choose longer period or distance criterion. 
In our case case it is even a bit more complicated because be subscribe independently for updates from different providers. Each of them has separate criteria. So we do some additional checks to have usable positions from all providers while keeping general user criteria.
My tests and frequent use of the application allowed my to tweak the algorithm, so that it works best for registering outdoor activities. But your millage may vary.
And my algorithm prefers GPS data over network, so it may explain more positions from GPS provider.

**Comment by TjrGithub** [comment]
Network positioning is available most of the time, as per satstat. However, ulogger never allows me to create network-only tracks.

**Comment by bfabiszewski** [comment]
Give me steps to reproduce it on Android 10.

It works for me if I choose 'Network' option in µlogger settings and turn on OS 'Location' setting.

**Comment by TjrGithub** [comment]
What I did:
* install Lineageos-microg https://download.lineage.microg.org/beryllium/lineage-17.1-20210115-microG-beryllium.zip
* install and configure offline location backends: https://f-droid.org/en/packages/org.fitchfamily.android.dejavu/, https://f-droid.org/en/packages/org.fitchfamily.android.gsmlocation/, perhaps also https://f-droid.org/en/packages/org.openbmap.unifiedNlp/
* check that satstat (from fdroid) gets a position fix
* install ulogger from fdroid
* configure uloggger: Preferences (every 5 seconds, no minimum distance, 5km accuracy, position from network only, no live sync, no server config, autostart on, metric units). 
* create a new track
* start it by swiping the green slider

expected result: track starts recording whenever NLP has a fix

acutal result: slider pops back to off

**Comment by bfabiszewski** [comment]
Might be an issue with third party location backends.
I plan to install Lineageos on one of my test devices. I may be able to tell more if I do so.

**Comment by bfabiszewski** [comment]
I did some testing. My setup is not exactly same as yours. My device doesn't have official LineageOS build.
I used [unofficial build](https://4pda.ru/pages/go/?u=https%3A%2F%2Fgithub.com%2FSamarV-121%2Freleases%2Freleases%2Fdownload%2Flineage-17.1-20200703-UNOFFICIAL-cactus-1249%2Flineage-17.1-20200703-UNOFFICIAL-cactus.zip&e=97941027), installed microG with [NanoDroid](https://downloads.nanolx.org/NanoDroid/Stable/NanoDroid-microG-23.1.2.20210117.zip) package and had to manually patch signature spoofing as no patcher worked for me.
I tested a bunch of location backends for UnifiedNlp. The best results I got from MozillaNlpBackend.

I was testing using µlogger 3.4 from F-Droid and also latest git version.

I can confirm that everything works fine using your setup.  Slider stays in on position. Locations are logged from network provider. If I choose to use both providers it also uses GPS position.

It is probably an issue with you particular setup. The problem you describe is very strange. If slider backs to off it means it cannot find any available provider. As you only selected network, it means somehow network provider is not visible to location manager. I don't have any experience with NLP but now I see it can be tricky and it seems something is wrong with your setup.

You may also check it in SatStat. It should show blue marker whenever it finds network based location. Do you ever get blue marker there?
